stages:
  binning:
    cmd: .venv/bin/python agroalimentary_quality_control/dataset/binning.py
      --original_data_set_path ${data.original_path}
      --data_set_path ${data.path}
      --n_bins ${data.n_bins}
      --target_col ${data.targets}
    deps:
    - agroalimentary_quality_control/dataset/binning.py
    - ${data.original_path}
  transform:
    cmd: .venv/bin/python agroalimentary_quality_control/dataset/transform.py
      --seed ${data.split.random_seed}
      --data_set_path ${data.path}
      --pics_path ${data.pics.path}
      --augs_per_pic ${data.augs.amt}
      --aug_pics_path ${data.augs.pics.path}
    deps:
    - agroalimentary_quality_control/dataset/transform.py
    - ${data.path}
  split:
    cmd: .venv/bin/python agroalimentary_quality_control/dataset/split.py
      --seed ${data.split.random_seed}
      --folds ${data.split.folds}
      --data_set_path ${data.path}
      --splits_path ${data.split.path}
      --train_set_file_name ${data.split.file_names.train_set}
      --test_set_file_name ${data.split.file_names.test_set}
      --val_set_file_name ${data.split.file_names.val_set}
      --target_col ${data.targets}
    deps:
    - agroalimentary_quality_control/dataset/split.py
    - ${data.path}
    - ${data.split.path}
  augment:
    cmd: .venv/bin/python agroalimentary_quality_control/dataset/augment.py
      --splits_path ${data.split.path}
      --pics_path ${data.pics.path}
      --aug_splits_path ${data.augs.split.path}
      --filename_col ${data.cols.filename}
      --aug_pics_path ${data.augs.pics.path}
      --augs_per_pic ${data.augs.amt}
    deps:
    - agroalimentary_quality_control/dataset/augment.py
    - ${data.split.path}
    - ${data.augs.split.path}
  fit:
    cmd: .venv/bin/python agroalimentary_quality_control/modeling/fit.py
      --models_path ${models_path}
      --aug_splits_path ${data.augs.split.path}
      --train_set_file_name ${data.split.file_names.train_set}
      --val_set_file_name ${data.split.file_names.val_set}
      --resize_ratio ${data.pics.resize_ratio}
      --epochs ${training.epochs}
      --batch_size ${training.batch_size}
      --patience ${training.patience}
      --weight_decay ${training.weight_decay}
      --learning_rate ${training.learning_rate}
      --seed ${training.random_seed}
      --repo_owner ${dagshub.repo_owner}
      --repo_name ${dagshub.repo_name}
      --experiment_name ${mlflow.experiment_name}
      --target_col ${data.targets}
      --pretrained_model_path ${pretrained.path}
      --pretrained_model_output_size ${pretrained.output_size}
      --filename_col ${data.cols.filename}
      --n_bins ${data.n_bins}
    deps:
    - agroalimentary_quality_control/modeling/fit.py
    - ${data.split.path}
    - ${pretrained.path}
    outs:
    - ${models_path}
  evaluate:
    cmd: .venv/bin/python agroalimentary_quality_control/modeling/evaluate.py
      --models_path ${models_path}
      --aug_splits_path ${data.augs.split.path}
      --test_set_file_name ${data.split.file_names.test_set}
      --aug_pics_path ${data.augs.pics.path}
      --resize_ratio ${data.pics.resize_ratio}
      --batch_size ${training.batch_size}
      --repo_owner ${dagshub.repo_owner}
      --repo_name ${dagshub.repo_name}
      --experiment_name ${mlflow.experiment_name}
      --target_col ${data.targets}
      --pretrained_model_path ${pretrained.path}
      --pretrained_model_output_size ${pretrained.output_size}
      --filename_col ${data.cols.filename}
      --pics_path ${data.pics.path}
    deps:
    - agroalimentary_quality_control/modeling/evaluate.py
    - ${data.augs.split.path}
    - ${models_path}