models_path: ./models/folds

data:
  split:
    random_seed: 42
    folds: 10
    path: /kaggle/working/dataset/splits
    file_names:
      train_set: train.csv
      test_set: test.csv
      val_set: val.csv
  path: /kaggle/input/rocket-dataset/data.csv
  pics:
    path: /kaggle/input/rocket-dataset/pics
    resize_ratio: 0.5
  targets: "chlorophyll ammonia"

training:
  epochs: 100
  batch_size: 64
  patience: 5
  learning_rate: 0.0001
  weight_decay: 0
  random_seed: 42

dagshub:
  repo_owner: GianmarcoTurchiano
  repo_name: Agroalimentary-Quality-Control

mlflow:
  experiment_name: '"Bidimensional output layer"'