pretrained:
  path: ./models/pretrained/mobilenet_v2_weights_best_acc.tar
  output_size: 1081

models_path: ./models/folds

data:
  cols:
    filename: fname
  split:
    random_seed: 42
    folds: 10
    path: /kaggle/working/dataset/splits
    file_names:
      train_set: train.csv
      test_set: test.csv
      val_set: val.csv
  path: /kaggle/input/rocket-dataset/data.csv
  pics:
    path: /kaggle/input/rocket-dataset/pics
    resize_ratio: 0.3
  targets: "chlorophyll ammonia"
  augs:
    split:
      path: /kaggle/working/dataset/aug_splits
    amt: 5
    pics:
      path: /kaggle/working/dataset/aug_pics

training:
  epochs: 50
  batch_size: 64
  patience: 10
  learning_rate: 1e-3
  weight_decay: 1e-3
  random_seed: 42

dagshub:
  repo_owner: GianmarcoTurchiano
  repo_name: Agroalimentary-Quality-Control

mlflow:
  experiment_name: '"Bidimensional output layer"'